### ISSUE TITLE
Oceania region sample count is inaccurate

### ISSUE THREAD

**Issue by rabdill** [blekhmanlab/compendium_website#21]
The metadata table and map both list the "Oceania" region as having zero samples, but it has four. Surprisingly, it looks like this *is* reflected in the "By Phylum" chart, but not elsewhere:
![image](https://github.com/blekhmanlab/compendium_website/assets/6011419/0c2343da-f74a-43ba-ba2d-8252c1aef6d0)

The first suspect was that the United States Minor Outlying Islands weren't properly categorized in a region, but this didn't resolve the issue. Vince said the problem was likely related to the compilation process starting with Natural Earth data and then merging in the compendium data, which may result in some mismatches that aren't obvious.

**Comment by vincerubinetti** [comment]
Thinking about this more, I think the best solution here is to fix the data. That is, for the entries `united states minor outlying islands:unspecified UM  Oceania`, fill in `UM` with the actual country codes.

Reasoning:

No matter what, we have to match some identifier in our data to some identifier in NE. NE has the actual shape geometry for the countries/regions, and without that, it can't show up on the map. In NE, there is no "UM" or "minor" or "outlying islands". I could add these keywords to the appropriate geometry shapes in the NE data, but it seems better to do it in our data.

Seems like the samples should be one of:
- Papua New Guinea (PG)
- Solomon Islands (SB)
- Vanuatu (VU)
- New Caledonia (NC)
- Fiji (FJ)

**Comment by vincerubinetti** [comment]
I'm incorrect. From my searching, "US Minor Outlying Islands" is a very official and concrete group of islands that are not any of the countries I listed above.

The problem is that they are I guess too small and below the resolution of the NE map data, so they are not even in it. We can't bump up to a higher resolution for bandwidth reasons.

I will try to modify my compile script in a way that it takes sample counts for regions directly from our data, and not with NE data as an in-between step.
